apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: datastream-deployment
spec:
  selector:
    matchLabels:
      app: datastream
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: datastream
    spec:
      containers:
      - name: datastream
        image: insanelyfreak/datastream
        ports:
        - containerPort: 80
apiVersion: apps/v1
kind: Service
metadata:
  name: datastream-service
spec:
  selector:
    app: datastream
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080       