apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-datastream
spec:
  selector:
    matchLabels:
      run: my-datastream
  replicas: 3
  template:
    metadata:
      labels:
        run: my-datastream
    spec:      
      containers:
      - name: my-app
        image: insanelyfreak/datastream
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-datastream
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
