apiVersion: v1
kind: Service
metadata:
  name: datastream-service
spec:
  # Expose the service on a static port on each node  
  type: NodePort

  # Access from outside cluster use nodePort i.e. 30163
  # Access inside cluster use port i.e. 9001
  # Access inside Pod use targetPort: 8080
  selector:
    app: datastream-pods

  ports:    
    - name: http
      protocol: TCP
      nodePort: 30163
      port: 9001
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastream-deployment
spec:
  selector:
    matchLabels:
      app: datastream-pods
  replicas: 1
  template:
    metadata:
      labels:
        app: datastream-pods
    spec:      
      containers:
      - name: datastream-app
        image: insanelyfreak/datastream
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: datastream-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datastream-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  - type: Pods
    pods:
      metric:
        name: packets-per-second
      target:
        type: AverageValue
        averageValue: 10
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1beta1
        kind: Ingress
        name: main-route
      target:
        type: Value
        value: 5
